INSERT INTO res_partner (
	id, 
	name,
	company_id,
	comment,
	create_date,
	color,
	active,
	street,
	user_id,
	zip,
	title,
	function,
	--country_id,
	parent_id,
	employee,
	type,
	email,
	vat,
	website,
	lang,
	city,
	street2,
	phone,
	credit_limit,
	write_date,
	date,
	tz,
	write_uid,
	display_name,
	create_uid,
	mobile,
	ref,
	is_company,
	--state_id,
	commercial_partner_id,
	signup_type,
	signup_expiration,
	signup_token,
	debit_limit,
	city_id,
	calendar_last_notif_ack,
	picking_warn,
	sale_warn,
	purchase_warn,
	invoice_warn_msg,
	picking_warn_msg,
	invoice_warn,
	purchase_warn_msg,
	sale_warn_msg,
    payment_next_action_date,
    payment_next_action,
    payment_note,
    payment_responsible_id
) SELECT
	agofer.id, 
	agofer.name, 
	agofer.company_id, 
	agofer.comment, 
	agofer.create_date, 
	agofer.color, 
	agofer.active, 
	agofer.street, 
	--agofer.user_id,
	2,
	agofer.zip, 
	agofer.title, 
	agofer.function, 
	--agofer.country_id, 
	agofer.parent_id, 
	agofer.employee, 
	agofer.type, 
	agofer.email, 
	agofer.vat, 
	agofer.website, 
	agofer.lang, 
	agofer.city, 
	agofer.street2, 
	agofer.phone, 
	agofer.credit_limit, 
	agofer.write_date, 
	agofer.date, 
	agofer.tz, 
	--agofer.write_uid, 
	2,
	agofer.display_name, 
	--agofer.create_uid,
	2,
	agofer.mobile, 
	agofer.ref, 
	agofer.is_company, 
	--agofer.state_id, 
	agofer.commercial_partner_id, 
	agofer.signup_type, 
	agofer.signup_expiration, 
	agofer.signup_token, 
	agofer.debit_limit, 
	agofer.city_id, 
	agofer.calendar_last_notif_ack, 
	agofer.picking_warn, 
	agofer.sale_warn, 
	agofer.purchase_warn, 
	agofer.invoice_warn_msg, 
	agofer.picking_warn_msg, 
	agofer.invoice_warn, 
	agofer.purchase_warn_msg, 
	agofer.sale_warn_msg,
	agofer.payment_next_action_date,
    agofer.payment_next_action,
    agofer.payment_note,
    --agofer.payment_responsible_id
	3
FROM dblink('dbname=agofer_08','select
	id, 
	name, 
	company_id, 
	comment, 
	create_date, 
	color, 
	active, 
	street, 
	user_id, 
	zip, 
	title, 
	function, 
	country_id, 
	parent_id, 
	employee, 
	type, 
	email, 
	vat, 
	website, 
	lang, 
	city, 
	street2, 
	phone, 
	credit_limit, 
	write_date, 
	date, 
	tz, 
	write_uid, 
	display_name, 
	create_uid, 
	mobile, 
	ref, 
	is_company, 
	state_id, 
	commercial_partner_id, 
	signup_type, 
	signup_expiration, 
	signup_token, 
	debit_limit, 
	city_id, 
	calendar_last_notif_ack, 
	picking_warn, 
	sale_warn, 
	purchase_warn, 
	invoice_warn_msg, 
	picking_warn_msg, 
	invoice_warn, 
	purchase_warn_msg, 
	sale_warn_msg,
	payment_next_action_date,
    payment_next_action,
    payment_note,
    payment_responsible_id
	from res_partner;'
) AS agofer(
	id integer, 
	name character varying, 
	company_id integer, 
	comment text, 
	create_date timestamp without time zone, 
	color integer, 
	active boolean, 
	street character varying, 
	user_id integer, 
	zip character varying, 
	title integer, 
	function character varying, 
	country_id integer, 
	parent_id integer, 
	employee boolean, 
	type character varying, 
	email character varying, 
	vat character varying, 
	website character varying, 
	lang character varying, 
	city character varying, 
	street2 character varying, 
	phone character varying, 
	credit_limit double precision, 
	write_date timestamp without time zone, 
	date date, 
	tz character varying, 
	write_uid integer, 
	display_name character varying, 
	create_uid integer, 
	mobile character varying, 
	ref character varying, 
	is_company boolean, 
	state_id integer, 
	commercial_partner_id integer, 
	signup_type character varying, 
	signup_expiration timestamp without time zone, 
	signup_token character varying, 
	debit_limit double precision, 
	city_id integer, 
	calendar_last_notif_ack timestamp without time zone, 
	picking_warn character varying, 
	sale_warn character varying, 
	purchase_warn character varying, 
	invoice_warn_msg text, 
	picking_warn_msg text, 
	invoice_warn character varying, 
	purchase_warn_msg text,
	sale_warn_msg text,
	payment_next_action_date date,
    payment_next_action text,
    payment_note text,
    payment_responsible_id integer
)
WHERE agofer.id NOT IN (SELECT id FROM res_partner);

select setval('res_partner_id_seq', (select max(id) from res_partner));

update res_partner as rp 
set state_id = rcs.id, country_id = rcc.id
from dblink('dbname=agofer_08','select rp.id, rc.name as rc_name, rcs.name as rcs_name, rcc.code as rcc_code
from res_partner rp
left join res_city rc on rc.id = rp.city_id 
left join res_country_state rcs on rcs.id = rp.state_id
left join res_country rcc on rcc.id = rp.country_id;') as agofer (id integer, rc_name character varying, rcs_name character varying, rcc_code character varying)
inner join res_country_state rcs on rcs.name = agofer.rcs_name 
inner join res_country rcc on rcc.code = agofer.rcc_code 
where agofer.id = rp.id;

update res_partner set credit_control = True, credit_type = 'insured' where credit_limit > 0 and parent_id is null;

update res_partner as rp
set first_name = agofer.primer_nombre, 
second_name = agofer.otros_nombres, 
first_surname = agofer.primer_apellido, 
second_surname = agofer.segundo_apellido, 
ref_num = agofer.ref
from dblink('dbname=agofer_08','select id,
primer_nombre, 
otros_nombres, 
primer_apellido, 
segundo_apellido,
ref
from res_partner;') agofer (id integer, 
primer_nombre character varying,
otros_nombres character varying,
primer_apellido character varying,
segundo_apellido character varying,
ref character varying)
where agofer.id = rp.id;