insert into stock_valuation_layer (create_date, 
write_uid, 
write_date, 
create_uid, 
company_id, 
product_id,
value,
quantity,
description)
select agofer.create_date, 
agofer.write_uid, 
agofer.write_date, 
agofer.create_uid, 
agofer.company_id, 
agofer.product_id,
agofer.cost,
agofer.qty,
cast(agofer.id as character varying)
from dblink('dbname=agofer_08',
            'select sq.id, 
sq.create_date, 
sq.write_uid, 
sq.write_date, 
sq.create_uid, 
sq.company_id, 
sq.product_id,
pt.uom_id,
sq.cost,
sq.qty,
sl.usage
from stock_quant sq 
inner join stock_location sl on sl.id = sq.location_id 
inner join product_product pp on pp.id = sq.product_id 
inner join product_template pt on pt.id = pp.product_tmpl_id;') as agofer(id integer, 
create_date timestamp without time zone, 
write_uid integer, 
write_date timestamp without time zone, 
create_uid integer, 
company_id integer, 
product_id integer, 
uom_id integer,
cost double precision,
qty double precision,
usage character varying) 
where agofer.usage = 'internal';