insert into purchase_order (
	id, 
	origin, 
	create_date, 
	company_id, 
	currency_id, 
	date_order, 
	dest_address_id, 
	create_uid, 
	amount_untaxed, 
	picking_type_id, 
	partner_id, 
	amount_tax, 
	state, 
	incoterm_id, 
	write_uid, 
	payment_term_id, 
	write_date, 
	partner_ref, 
	date_approve, 
	amount_total, 
	name, 
	notes
) select 
	agofer.id, 
	agofer.origin, 
	agofer.create_date, 
	agofer.company_id, 
	agofer.currency_id, 
	agofer.date_order, 
	agofer.dest_address_id, 
	agofer.create_uid, 
	agofer.amount_untaxed, 
	agofer.picking_type_id, 
	agofer.partner_id, 
	agofer.amount_tax, 
	agofer.state, 
	agofer.incoterm_id, 
	agofer.write_uid, 
	agofer.payment_term_id, 
	agofer.write_date, 
	agofer.partner_ref, 
	agofer.date_approve, 
	agofer.amount_total, 
	agofer.name, 
	agofer.notes
from dblink('dbname=agofer_08', 'select 
	id, 
	origin, 
	create_date, 
	company_id, 
	currency_id, 
	date_order, 
	dest_address_id, 
	create_uid, 
	amount_untaxed, 
	picking_type_id, 
	partner_id, 
	amount_tax, 
	state, 
	incoterm_id, 
	write_uid, 
	payment_term_id, 
	write_date, 
	partner_ref, 
	date_approve, 
	amount_total, 
	name, 
	notes
	from purchase_order;'
) as agofer (
	id integer, 
	origin character varying, 
	create_date timestamp without time zone, 
	company_id integer, 
	currency_id integer, 
	date_order timestamp without time zone, 
	dest_address_id integer, 
	create_uid integer, 
	amount_untaxed numeric, 
	picking_type_id integer, 
	partner_id integer, 
	amount_tax numeric, 
	state character varying, 
	incoterm_id integer, 
	write_uid integer, 
	payment_term_id integer, 
	write_date timestamp without time zone, 
	partner_ref character varying, 
	date_approve date, 
	amount_total numeric, 
	name character varying, 
	notes text
);

select setval('purchase_order_id_seq', (select max(id) from purchase_order));