insert into purchase_order_line (
	id, 
	create_date, 
	product_uom, 
	order_id, 
	price_unit, 
	write_uid, 
	write_date, 
	product_qty, 
	partner_id, 
	product_id, 
	create_uid, 
	name, 
	date_planned, 
	company_id, 
	state, 
	account_analytic_id
) select 
	agofer.id, 
	agofer.create_date, 
	agofer.product_uom, 
	agofer.order_id, 
	agofer.price_unit, 
	agofer.write_uid, 
	agofer.write_date, 
	agofer.product_qty, 
	agofer.partner_id, 
	agofer.product_id, 
	agofer.create_uid, 
	agofer.name, 
	agofer.date_planned, 
	agofer.company_id, 
	agofer.state, 
	agofer.account_analytic_id
from dblink('dbname=agofer_08', 'select 
	id, 
	create_date, 
	product_uom, 
	order_id, 
	price_unit, 
	write_uid, 
	write_date, 
	product_qty, 
	partner_id, 
	product_id, 
	create_uid, 
	name, 
	date_planned, 
	company_id, 
	state, 
	account_analytic_id
	from purchase_order_line;'
) as agofer (
	id integer, 
	create_date timestamp without time zone, 
	product_uom integer, 
	order_id integer, 
	price_unit numeric, 
	write_uid integer, 
	write_date timestamp without time zone, 
	product_qty numeric, 
	partner_id integer, 
	product_id integer, 
	create_uid integer, 
	name text, 
	date_planned date, 
	company_id integer, 
	state character varying, 
	account_analytic_id integer
);

select setval('purchase_order_line_id_seq', (select max(id) from purchase_order_line));