insert into hr_employee (
	id, 
	address_id, 
	create_date, 
	coach_id, 
	resource_id, 
	color, 
	marital, 
	job_id, 
	work_phone, 
	country_id, 
	bank_account_id, 
	parent_id, 
	department_id, 
	mobile_phone, 
	create_uid, 
	birthday, 
	write_date, 
	sinid, 
	write_uid, 
	work_email, 
	work_location, 
	notes, 
	passport_id, 
	gender, 
	ssnid, 
	children, 
	vehicle, 
	place_of_birth,
	company_id
) select 
	agofer.id, 
	agofer.address_id, 
	agofer.create_date, 
	agofer.coach_id, 
	agofer.resource_id, 
	agofer.color, 
	agofer.marital, 
	agofer.job_id, 
	agofer.work_phone, 
	agofer.country_id, 
	agofer.bank_account_id, 
	agofer.parent_id, 
	agofer.department_id, 
	agofer.mobile_phone, 
	agofer.create_uid, 
	agofer.birthday, 
	agofer.write_date, 
	agofer.sinid, 
	agofer.write_uid, 
	agofer.work_email, 
	agofer.work_location, 
	agofer.notes, 
	agofer.passport_id, 
	agofer.gender, 
	agofer.ssnid, 
	agofer.children, 
	agofer.vehicle, 
	agofer.place_of_birth,
	--agofer.company_id
	1
from dblink('dbname=agofer_08','SELECT 
	id, 
	address_id, 
	create_date, 
	coach_id, 
	resource_id, 
	color, 
	marital, 
	job_id, 
	work_phone, 
	country_id, 
	bank_account_id, 
	parent_id, 
	department_id, 
	mobile_phone, 
	create_uid, 
	birthday, 
	write_date, 
	sinid, 
	write_uid, 
	work_email, 
	work_location, 
	notes, 
	passport_id, 
	gender, 
	ssnid, 
	children, 
	vehicle, 
	place_of_birth
	FROM hr_employee;'
) as agofer(
	id integer, 
	address_id integer, 
	create_date timestamp without time zone, 
	coach_id integer, 
	resource_id integer, 
	color integer, 
	marital character varying, 
	job_id integer, 
	work_phone character varying, 
	country_id integer, 
	bank_account_id integer, 
	parent_id integer, 
	department_id integer, 
	mobile_phone character varying, 
	create_uid integer, 
	birthday date, 
	write_date timestamp without time zone, 
	sinid character varying, 
	write_uid integer, 
	work_email character varying, 
	work_location character varying, 
	notes text, 
	passport_id character varying, 
	gender character varying, 
	ssnid character varying, 
	children integer, 
	vehicle character varying, 
	place_of_birth character varying
);