ALTER TABLE hr_employee DISABLE TRIGGER ALL;
DELETE FROM hr_employee;
ALTER TABLE hr_employee ENABLE TRIGGER ALL;

INSERT INTO hr_employee (
	id,
	address_id,
	create_date,
	coach_id,
	resource_id,
	color,
	marital,
	job_id,
	work_phone,
	country_id,
	bank_account_id,
	parent_id,
	department_id,
	mobile_phone,
	create_uid,
	birthday,
	write_date,
	sinid,
	write_uid,
	work_email,
	work_location,
	notes,
	passport_id,
	gender,
	ssnid,
	children,
	vehicle,
	place_of_birth,
	company_id,
	active,
	partner_id,
    user_partner_id
) SELECT
	agofer.id,
	agofer.address_id,
	agofer.create_date,
	agofer.coach_id,
	agofer.resource_id,
	agofer.color,
	--agofer.marital,
	(case when agofer.marital = 'common-law relationship' then 'cohabitant' else agofer.marital end),
	agofer.job_id,
	agofer.work_phone,
	agofer.country_id,
	agofer.bank_account_id,
	agofer.parent_id,
	agofer.department_id,
	agofer.mobile_phone,
	agofer.create_uid,
	agofer.birthday,
	agofer.write_date,
	agofer.sinid,
	agofer.write_uid,
	agofer.work_email,
	agofer.work_location,
	agofer.notes,
	agofer.passport_id,
	agofer.gender,
	agofer.ssnid,
	agofer.children,
	agofer.vehicle,
	agofer.place_of_birth,
	--agofer.company_id
	1,
	agofer.active,
	agofer.partner_id,
    --agofer.user_partner_id
    null
FROM dblink('dbname=agofer_08','select
	HE.id,
	HE.address_id,
	HE.create_date,
	HE.coach_id,
	HE.resource_id,
	HE.color,
	HE.marital,
	HE.job_id,
	HE.work_phone,
	HE.country_id,
	HE.bank_account_id,
	HE.parent_id,
	HE.department_id,
	HE.mobile_phone,
	HE.create_uid,
	HE.birthday,
	HE.write_date,
	HE.sinid,
	HE.write_uid,
	HE.work_email,
	HE.work_location,
	HE.notes,
	HE.passport_id,
	HE.gender,
	HE.ssnid,
	HE.children,
	HE.vehicle,
	HE.place_of_birth,
	RR.active,
	RR.partner_id
	from hr_employee HE
	inner join resource_resource as RR on RR.id = HE.resource_id;'
) AS agofer(
	id integer,
	address_id integer,
	create_date timestamp without time zone,
	coach_id integer,
	resource_id integer,
	color integer,
	marital character varying,
	job_id integer,
	work_phone character varying,
	country_id integer,
	bank_account_id integer,
	parent_id integer,
	department_id integer,
	mobile_phone character varying,
	create_uid integer,
	birthday date,
	write_date timestamp without time zone,
	sinid character varying,
	write_uid integer,
	work_email character varying,
	work_location character varying,
	notes text,
	passport_id character varying,
	gender character varying,
	ssnid character varying,
	children integer,
	vehicle character varying,
	place_of_birth character varying,
	active boolean,
	partner_id integer
);

select setval('hr_employee_id_seq', (select max(id) from hr_employee));

update hr_employee he 
set name = rp.name 
from res_partner rp 
where rp.id = he.partner_id;