insert into wage_update_history (id, 
wage, 
create_uid, 
user_id, 
contract_id, 
write_uid, 
write_date, 
date, 
create_date, 
company_id)
select agofer.id, 
agofer.wage, 
agofer.create_uid, 
agofer.user_id, 
agofer.contract_id, 
agofer.write_uid, 
agofer.write_date, 
agofer.date, 
agofer.create_date,
1
from dblink('dbname=agofer_08',
            'select id, 
wage, 
create_uid, 
user_id, 
contract_id, 
write_uid, 
write_date, 
date, 
create_date 
from hr_contract_salary_change;') as agofer(id integer, 
wage numeric, 
create_uid integer, 
user_id integer, 
contract_id integer, 
write_uid integer, 
write_date timestamp without time zone, 
date timestamp without time zone, 
create_date timestamp without time zone);

select setval('wage_update_history_id_seq', (select max(id) from wage_update_history));