insert into res_bank (
	id, 
	city, 
	create_date, 
	name, 
	zip, 
	create_uid, 
	country, 
	street2, 
	bic, 
	phone, 
	state, 
	street, 
	write_date, 
	active, 
	write_uid, 
	email
) select 
	agofer.id, 
	agofer.city, 
	agofer.create_date, 
	agofer.name, 
	agofer.zip, 
	agofer.create_uid, 
	agofer.country, 
	agofer.street2, 
	agofer.bic, 
	agofer.phone, 
	agofer.state, 
	agofer.street, 
	agofer.write_date, 
	agofer.active, 
	agofer.write_uid, 
	agofer.email
from dblink('dbname=agofer_08','SELECT 
	id, 
	city, 
	create_date, 
	name, 
	zip, 
	create_uid, 
	country, 
	street2, 
	bic, 
	phone, 
	state, 
	street, 
	write_date, 
	active, 
	write_uid, 
	email
	FROM res_bank;'
) as agofer(
	id integer, 
	city character varying, 
	create_date timestamp without time zone, 
	name character varying, 
	zip character varying, 
	create_uid integer, 
	country integer, 
	street2 character varying, 
	bic character varying, 
	phone character varying, 
	state integer, 
	street character varying, 
	write_date timestamp without time zone, 
	active boolean, 
	write_uid integer, 
	email character varying
) where agofer.id not in (select id from res_bank);