UPDATE res_company AS rc 
SET name = agofer.name, 
	partner_id = agofer.partner_id, 
	currency_id = agofer.currency_id, 
	create_date = agofer.create_date, 
	write_uid = agofer.write_uid, 
	logo_web = agofer.logo_web, 
	-- font = agofer.font, 
	parent_id = agofer.parent_id, 
	email = agofer.email, 
	create_uid = agofer.create_uid, 
	phone = agofer.phone, 
	write_date = agofer.write_date, 
	company_registry = agofer.company_registry, 
	-- paperformat_id = agofer.paperformat_id, 
	expects_chart_of_accounts = agofer.expects_chart_of_accounts, 
	expense_currency_exchange_account_id = agofer.expense_currency_exchange_account_id, 
	tax_calculation_rounding_method = agofer.tax_calculation_rounding_method, 
	income_currency_exchange_account_id = agofer.income_currency_exchange_account_id, 
	internal_transit_location_id = agofer.internal_transit_location_id, 
	po_lead = agofer.po_lead, 
	security_lead = agofer.security_lead, 
	manufacturing_lead = agofer.manufacturing_lead 
FROM dblink('dbname=agofer_08', 'select
	id, 
	name, 
	partner_id, 
	currency_id, 
	create_date, 
	write_uid, 
	logo_web, 
	font, 
	parent_id, 
	email, 
	create_uid, 
	phone, 
	write_date, 
	company_registry, 
	paperformat_id, 
	expects_chart_of_accounts, 
	expense_currency_exchange_account_id, 
	tax_calculation_rounding_method, 
	income_currency_exchange_account_id, 
	internal_transit_location_id, 
	po_lead, 
	security_lead, 
	manufacturing_lead 
    from res_company;'
) AS agofer (
	id integer, 
	name character varying, 
	partner_id integer, 
	currency_id integer, 
	create_date timestamp without time zone, 
	write_uid integer, 
	logo_web bytea, 
	font integer, 
	parent_id integer, 
	email character varying, 
	create_uid integer, 
	phone character varying, 
	write_date timestamp without time zone, 
	company_registry character varying, 
	paperformat_id integer, 
	expects_chart_of_accounts boolean, 
	expense_currency_exchange_account_id integer, 
	tax_calculation_rounding_method character varying, 
	income_currency_exchange_account_id integer, 
	internal_transit_location_id integer, 
	po_lead double precision, 
	security_lead double precision, 
	manufacturing_lead double precision
)
WHERE rc.id = agofer.id;